services:
  - type: web
    name: hotel-scraper
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium
      - key: PYTHONUNBUFFERED
        value: "1"
